import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
function when(ts){ return ts ? new Date(ts).toLocaleString() : ""; }
function label(n){ const who=n.actor?.display_name||n.actor?.username||"DWMY"; if(n.notification_type==="REPLY") return `${who} replied to your post`; if(n.notification_type==="MENTION") return `${who} mentioned you`; if(n.notification_type==="REACTION") return `${who} liked your post`; if(n.notification_type==="DIRECT_MESSAGE") return `${who} sent you a message`; return `${who}: ${n.notification_type.toLowerCase()}`; }
export default function Notifications({ onOpenPost, onOpenMessage, onChanged }){
 const [tab,setTab]=useState("active"),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){ setLoading(true); setError(""); let q=supabase.from("notifications").select(`id,notification_type,discussion_id,post_id,message_conversation_id,message_id,is_read,created_at,read_at,archived_at,actor:profiles!notifications_actor_user_id_fkey(id,username,display_name)`).order("created_at",{ascending:false}).limit(200); q=tab==="active"?q.is("archived_at",null):q.not("archived_at","is",null); const {data,error}=await q; if(error)setError(error.message); else setRows(data||[]); setLoading(false); }
 useEffect(()=>{load();},[tab]);
 async function open(n){ const {error}=await supabase.rpc("open_notification",{target_notification_id:n.id}); if(error){setError(error.message);return;} onChanged?.(); if(n.notification_type==="DIRECT_MESSAGE"&&n.message_conversation_id) onOpenMessage(n.message_conversation_id,n.message_id); else if(n.discussion_id) onOpenPost(n.discussion_id,n.post_id); }
 async function archive(id){ const {error}=await supabase.rpc("archive_notification",{target_notification_id:id}); if(error)setError(error.message); else {await load();onChanged?.();} }
 async function restore(id){ const {error}=await supabase.rpc("restore_notification",{target_notification_id:id}); if(error)setError(error.message); else {await load();onChanged?.();} }
 async function clearAll(){ const {error}=await supabase.rpc("archive_all_notifications"); if(error)setError(error.message); else {await load();onChanged?.();} }
 return <section className="notification-center"><div className="page-title-row"><div><span className="eyebrow">DWMY ACTIVITY</span><h1>Notification Center</h1><p>Active notifications disappear after opening, but remain available in Archive.</p></div>{tab==="active"&&rows.length>0&&<button className="dwmy-action-button" onClick={clearAll}>Clear Active</button>}</div><div className="notification-tabs"><button className={tab==="active"?"active":""} onClick={()=>setTab("active")}>Active</button><button className={tab==="archive"?"active":""} onClick={()=>setTab("archive")}>Archive</button></div>{error&&<div className="discussion-open-error">{error}</div>}{loading?<div className="market-directory-state">Loading notifications...</div>:rows.length===0?<div className="market-directory-state">{tab==="active"?"You're caught up.":"No archived notifications yet."}</div>:<div className="notification-list">{rows.map(n=><article className="notification-row" key={n.id}><button className="notification-main" onClick={()=>open(n)}><strong>{label(n)}</strong><span>{when(n.created_at)}</span></button>{tab==="active"?<button className="dwmy-text-button" onClick={()=>archive(n.id)}>Archive</button>:<button className="dwmy-text-button" onClick={()=>restore(n.id)}>Restore</button>}</article>)}</div>}</section>;
}
