-- DWMY Market Directory V2
-- Optional groups + broad canonical seed + activity discovery.
-- Existing instrument IDs and D/W/M/Y discussion identities are preserved.

begin;

create table if not exists public.market_groups (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.sections(id) on delete cascade,
  name text not null,
  slug text not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(section_id, slug)
);

alter table public.market_groups enable row level security;

drop policy if exists "market_groups_read_authenticated" on public.market_groups;
create policy "market_groups_read_authenticated"
on public.market_groups for select
to authenticated
using (true);

alter table public.instruments
  add column if not exists group_id bigint references public.market_groups(id) on delete set null;

create index if not exists idx_instruments_group_id on public.instruments(group_id);
create index if not exists idx_market_groups_section_sort on public.market_groups(section_id, sort_order);

-- Canonical market sections. Existing rows are reused.
insert into public.sections (name, slug, description, section_type, sort_order, is_active)
select v.name, v.slug, v.description, 'MARKET', v.sort_order, true
from (values
  ('Indices','indices','Major equity indices and index markets',30),
  ('Crypto','crypto','Digital asset markets',50)
) as v(name,slug,description,sort_order)
where not exists (select 1 from public.sections s where s.slug=v.slug);

-- Groups.
with wanted(section_slug, name, slug, description, sort_order) as (
  values
  ('fx','Majors','majors','Major U.S. dollar currency pairs',10),
  ('fx','Crosses','crosses','Major non-U.S.-dollar currency crosses',20),
  ('equities','Major U.S. Equities','major-us-equities','Widely followed U.S. listed equities and ETFs',10),
  ('indices','U.S. Indices','us-indices','Major U.S. equity indices',10),
  ('commodities','Metals','metals','Precious metal markets',10),
  ('commodities','Energy','energy','Major energy markets',20),
  ('crypto','Major Crypto','major-crypto','Widely followed digital assets',10)
)
insert into public.market_groups(section_id,name,slug,description,sort_order,is_active)
select s.id,w.name,w.slug,w.description,w.sort_order,true
from wanted w join public.sections s on s.slug=w.section_slug
where not exists (
  select 1 from public.market_groups g
  where g.section_id=s.id and g.slug=w.slug
);

-- Assign existing canonical instruments to groups where recognizable.
update public.instruments i set group_id=g.id
from public.sections s, public.market_groups g
where i.section_id=s.id and g.section_id=s.id
  and s.slug='fx' and g.slug='majors'
  and i.symbol in ('EUR/USD','GBP/USD','USD/JPY','USD/CHF','USD/CAD','AUD/USD','NZD/USD');

update public.instruments i set group_id=g.id
from public.sections s, public.market_groups g
where i.section_id=s.id and g.section_id=s.id
  and s.slug='equities' and g.slug='major-us-equities';

update public.instruments i set group_id=g.id
from public.sections s, public.market_groups g
where i.section_id=s.id and g.section_id=s.id
  and s.slug='commodities' and g.slug='metals'
  and i.symbol in ('XAU/USD','XAG/USD');

-- Broad initial universe. Does NOT pre-create discussions.
with wanted(section_slug, group_slug, symbol, slug, name, description, sort_order) as (
  values
  -- FX majors
  ('fx','majors','EUR/USD','eur-usd','Euro / U.S. Dollar',null,10),
  ('fx','majors','GBP/USD','gbp-usd','British Pound / U.S. Dollar',null,20),
  ('fx','majors','USD/JPY','usd-jpy','U.S. Dollar / Japanese Yen',null,30),
  ('fx','majors','USD/CHF','usd-chf','U.S. Dollar / Swiss Franc',null,40),
  ('fx','majors','USD/CAD','usd-cad','U.S. Dollar / Canadian Dollar',null,50),
  ('fx','majors','AUD/USD','aud-usd','Australian Dollar / U.S. Dollar',null,60),
  ('fx','majors','NZD/USD','nzd-usd','New Zealand Dollar / U.S. Dollar',null,70),
  -- FX crosses
  ('fx','crosses','EUR/GBP','eur-gbp','Euro / British Pound',null,10),
  ('fx','crosses','EUR/JPY','eur-jpy','Euro / Japanese Yen',null,20),
  ('fx','crosses','EUR/CHF','eur-chf','Euro / Swiss Franc',null,30),
  ('fx','crosses','EUR/AUD','eur-aud','Euro / Australian Dollar',null,40),
  ('fx','crosses','EUR/CAD','eur-cad','Euro / Canadian Dollar',null,50),
  ('fx','crosses','GBP/JPY','gbp-jpy','British Pound / Japanese Yen',null,60),
  ('fx','crosses','GBP/CHF','gbp-chf','British Pound / Swiss Franc',null,70),
  ('fx','crosses','GBP/AUD','gbp-aud','British Pound / Australian Dollar',null,80),
  ('fx','crosses','GBP/CAD','gbp-cad','British Pound / Canadian Dollar',null,90),
  ('fx','crosses','AUD/JPY','aud-jpy','Australian Dollar / Japanese Yen',null,100),
  ('fx','crosses','AUD/NZD','aud-nzd','Australian Dollar / New Zealand Dollar',null,110),
  ('fx','crosses','CAD/JPY','cad-jpy','Canadian Dollar / Japanese Yen',null,120),
  ('fx','crosses','CHF/JPY','chf-jpy','Swiss Franc / Japanese Yen',null,130),
  -- equities
  ('equities','major-us-equities','MSFT','msft','Microsoft',null,40),
  ('equities','major-us-equities','AMZN','amzn','Amazon',null,50),
  ('equities','major-us-equities','META','meta','Meta Platforms',null,60),
  ('equities','major-us-equities','GOOGL','googl','Alphabet',null,70),
  ('equities','major-us-equities','TSLA','tsla','Tesla',null,80),
  ('equities','major-us-equities','AMD','amd','Advanced Micro Devices',null,90),
  ('equities','major-us-equities','NFLX','nflx','Netflix',null,100),
  ('equities','major-us-equities','JPM','jpm','JPMorgan Chase',null,110),
  ('equities','major-us-equities','BRK.B','brk-b','Berkshire Hathaway Class B',null,120),
  ('equities','major-us-equities','SPY','spy','SPDR S&P 500 ETF Trust',null,130),
  ('equities','major-us-equities','QQQ','qqq','Invesco QQQ Trust',null,140),
  -- indices
  ('indices','us-indices','SPX','spx','S&P 500 Index',null,10),
  ('indices','us-indices','NDX','ndx','Nasdaq-100 Index',null,20),
  ('indices','us-indices','DJI','dji','Dow Jones Industrial Average',null,30),
  ('indices','us-indices','RUT','rut','Russell 2000 Index',null,40),
  -- commodities
  ('commodities','metals','XAU/USD','xau-usd','Gold / U.S. Dollar',null,10),
  ('commodities','metals','XAG/USD','xag-usd','Silver / U.S. Dollar',null,20),
  ('commodities','energy','WTI','wti','West Texas Intermediate Crude Oil',null,10),
  ('commodities','energy','BRENT','brent','Brent Crude Oil',null,20),
  ('commodities','energy','NATGAS','natgas','Natural Gas',null,30),
  -- crypto
  ('crypto','major-crypto','BTC/USD','btc-usd','Bitcoin / U.S. Dollar',null,10),
  ('crypto','major-crypto','ETH/USD','eth-usd','Ethereum / U.S. Dollar',null,20),
  ('crypto','major-crypto','SOL/USD','sol-usd','Solana / U.S. Dollar',null,30),
  ('crypto','major-crypto','XRP/USD','xrp-usd','XRP / U.S. Dollar',null,40),
  ('crypto','major-crypto','BNB/USD','bnb-usd','BNB / U.S. Dollar',null,50),
  ('crypto','major-crypto','ADA/USD','ada-usd','Cardano / U.S. Dollar',null,60),
  ('crypto','major-crypto','DOGE/USD','doge-usd','Dogecoin / U.S. Dollar',null,70),
  ('crypto','major-crypto','AVAX/USD','avax-usd','Avalanche / U.S. Dollar',null,80),
  ('crypto','major-crypto','LINK/USD','link-usd','Chainlink / U.S. Dollar',null,90)
)
insert into public.instruments(section_id,group_id,symbol,slug,name,description,sort_order,is_active)
select s.id,g.id,w.symbol,w.slug,w.name,w.description,w.sort_order,true
from wanted w
join public.sections s on s.slug=w.section_slug
left join public.market_groups g on g.section_id=s.id and g.slug=w.group_slug
where not exists (
  select 1 from public.instruments i
  where i.section_id=s.id and (i.slug=w.slug or i.symbol=w.symbol)
);

-- Ensure pre-existing matching instruments inherit their intended groups.
with assignments(section_slug,group_slug,symbol) as (
  values
  ('fx','majors','EUR/USD'),('fx','majors','GBP/USD'),('fx','majors','USD/JPY'),
  ('fx','majors','USD/CHF'),('fx','majors','USD/CAD'),('fx','majors','AUD/USD'),('fx','majors','NZD/USD'),
  ('fx','crosses','EUR/GBP'),('fx','crosses','EUR/JPY'),('fx','crosses','EUR/CHF'),('fx','crosses','EUR/AUD'),
  ('fx','crosses','EUR/CAD'),('fx','crosses','GBP/JPY'),('fx','crosses','GBP/CHF'),('fx','crosses','GBP/AUD'),
  ('fx','crosses','GBP/CAD'),('fx','crosses','AUD/JPY'),('fx','crosses','AUD/NZD'),('fx','crosses','CAD/JPY'),('fx','crosses','CHF/JPY'),
  ('commodities','metals','XAU/USD'),('commodities','metals','XAG/USD'),
  ('commodities','energy','WTI'),('commodities','energy','BRENT'),('commodities','energy','NATGAS'),
  ('indices','us-indices','SPX'),('indices','us-indices','NDX'),('indices','us-indices','DJI'),('indices','us-indices','RUT'),
  ('crypto','major-crypto','BTC/USD'),('crypto','major-crypto','ETH/USD'),('crypto','major-crypto','SOL/USD'),
  ('crypto','major-crypto','XRP/USD'),('crypto','major-crypto','BNB/USD'),('crypto','major-crypto','ADA/USD'),
  ('crypto','major-crypto','DOGE/USD'),('crypto','major-crypto','AVAX/USD'),('crypto','major-crypto','LINK/USD')
)
update public.instruments i
set group_id=g.id
from assignments a
join public.sections s on s.slug=a.section_slug
join public.market_groups g on g.section_id=s.id and g.slug=a.group_slug
where i.section_id=s.id and i.symbol=a.symbol;

-- Equities all currently live under one broad group.
update public.instruments i set group_id=g.id
from public.sections s
join public.market_groups g on g.section_id=s.id and g.slug='major-us-equities'
where i.section_id=s.id and s.slug='equities' and i.group_id is null;

-- Discovery RPC: "Top Traders" = highest contribution counts in that instrument.
-- This is participation/activity terminology, not profitability or trading performance.
create or replace function public.get_market_discovery(
  market_limit integer default 9,
  trader_limit integer default 3,
  lookback_days integer default 7
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
with active_instruments as (
  select
    i.id instrument_id,
    i.symbol,
    i.slug instrument_slug,
    i.name instrument_name,
    i.description instrument_description,
    i.sort_order instrument_sort_order,
    s.id section_id,
    s.name section_name,
    s.slug section_slug,
    s.description section_description,
    g.name group_name
  from public.instruments i
  join public.sections s on s.id=i.section_id
  left join public.market_groups g on g.id=i.group_id
  where i.is_active=true and s.is_active=true and s.section_type='MARKET'
),
recent_posts as (
  select d.instrument_id,p.author_id,p.created_at
  from public.posts p
  join public.discussions d on d.id=p.discussion_id
  where p.is_deleted=false
    and d.is_deleted=false
    and d.instrument_id is not null
    and p.created_at >= now() - make_interval(days => greatest(1,least(coalesce(lookback_days,7),365)))
),
activity as (
  select
    ai.*,
    count(rp.author_id)::bigint contribution_count,
    count(distinct rp.author_id)::bigint trader_count,
    max(rp.created_at) latest_activity_at
  from active_instruments ai
  left join recent_posts rp on rp.instrument_id=ai.instrument_id
  group by ai.instrument_id,ai.symbol,ai.instrument_slug,ai.instrument_name,
           ai.instrument_description,ai.instrument_sort_order,
           ai.section_id,ai.section_name,ai.section_slug,ai.section_description,ai.group_name
),
ranked as (
  select * from activity
  order by contribution_count desc, latest_activity_at desc nulls last,
           section_name, instrument_sort_order, symbol
  limit greatest(1,least(coalesce(market_limit,9),50))
)
select coalesce(jsonb_agg(
  jsonb_build_object(
    'instrument_id',r.instrument_id,
    'group_name',r.group_name,
    'contribution_count',r.contribution_count,
    'trader_count',r.trader_count,
    'latest_activity_at',r.latest_activity_at,
    'section',jsonb_build_object(
      'id',r.section_id,'name',r.section_name,'slug',r.section_slug,'description',r.section_description
    ),
    'instrument',jsonb_build_object(
      'id',r.instrument_id,'section_id',r.section_id,'symbol',r.symbol,
      'slug',r.instrument_slug,'name',r.instrument_name,'description',r.instrument_description
    ),
    'top_traders',coalesce((
      select jsonb_agg(x.obj order by x.contributions desc, x.username)
      from (
        select
          count(*)::bigint contributions,
          pr.username,
          pr.display_name,
          jsonb_build_object(
            'user_id',rp.author_id,
            'username',pr.username,
            'display_name',pr.display_name,
            'contributions',count(*)::bigint
          ) obj
        from recent_posts rp
        join public.profiles pr on pr.id=rp.author_id
        where rp.instrument_id=r.instrument_id
        group by rp.author_id,pr.username,pr.display_name
        order by count(*) desc,pr.username
        limit greatest(1,least(coalesce(trader_limit,3),10))
      ) x
    ),'[]'::jsonb)
  )
  order by r.contribution_count desc,r.latest_activity_at desc nulls last,r.section_name,r.instrument_sort_order
),'[]'::jsonb)
from ranked r;
$$;

revoke all on function public.get_market_discovery(integer,integer,integer) from public;
grant execute on function public.get_market_discovery(integer,integer,integer) to authenticated;

commit;

-- Acceptance
select s.name section_name,g.name group_name,count(i.id) instruments
from public.sections s
left join public.market_groups g on g.section_id=s.id and g.is_active=true
left join public.instruments i on i.section_id=s.id and i.group_id=g.id and i.is_active=true
where s.section_type='MARKET' and s.is_active=true
group by s.name,s.sort_order,g.name,g.sort_order
order by s.sort_order,g.sort_order,g.name;

select public.get_market_discovery(9,3,7);
